# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    container_name: 'mongo-reactive'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: product-db
    ports:
      - '27017-27019:27017-27019'